services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n-local
    restart: always
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=development
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=America/Santiago
    volumes:
      - n8n_data_local:/home/node/.n8n
    ports:
      - "5678:5678"
    networks:
      - proxy

volumes:
  n8n_data_local:


networks:
  proxy:
    external: true
